package eu.kanade.tachiyomi.extension

/** Per-extension BuildConfig stub — auto-generated by AGP in Android builds. */
object BuildConfig {
    const val VERSION_CODE = 1
    const val VERSION_NAME = "1.0"
    const val APPLICATION_ID = "eu.kanade.tachiyomi.extension"
    const val DEBUG = false
}
